### ISSUE TITLE
All values 0

### ISSUE THREAD

**Issue by janmatias** [sindrebroch/ha-pollenvarsel#2] opened 2022-04-30 17:58 UTC
After I install this, all values are always zero. Can’t find anything logged by this integration either. How should I go about finding the issue? :)

**Comment by sindrebroch** [comment] 2022-04-30 18:03
I just released a new version. Can you try to update and see if it fixes it? 

If not, diagnostics are now implemented, so you can download diagnostics on the device-page, and add them to the issue to help with debugging.

**Comment by Gyldenlow** [comment] 2022-05-02 11:33
On that note, what do the different values mean?

**Comment by sindrebroch** [comment] 2022-05-02 16:18
Seems to me that the values are between 0 and 1, where 0 is no pollen, 1 is max. 

I think the available values are 0, 0.25, 0.5, 0.75, 1

**Comment by sindrebroch** [comment] 2022-05-02 16:19
@janmatias is the issue resolved with the new update?

**Comment by Eivind007** [comment] 2022-05-02 17:31
![image](https://user-images.githubusercontent.com/94549742/166295390-9deab5ef-d257-4253-bedf-eb321fda9665.png)
![image](https://user-images.githubusercontent.com/94549742/166295521-2f493323-b58e-4d0a-8d11-7a26816c021c.png)

There seems to be an issue with values for today versus values for tomorrow

**Comment by sindrebroch** [comment] 2022-05-02 17:50
@Eivind007 Weird! Mine is correct for Oslo but not Hordaland. Will look into it, haven't really checked that the other areas works as expected.

Thanks for your issue. Easy to reproduce and with reference

**Comment by sindrebroch** [comment] 2022-05-02 18:36
I think I found the issue, but I need some more time to test the API. 

Appearantly I get a different response when calling the API with unix timestamp ?t=1651513650158. Maybe the forecast changes throughout the day.

**Comment by sindrebroch** [comment] 2022-05-02 18:57
@Eivind007 I released a version 1.3.1 with timestamp added to the request. Can you test if that works better for you?

**Comment by Eivind007** [comment] 2022-05-02 19:18
![image](https://user-images.githubusercontent.com/94549742/166311010-cbe5e906-3238-47dc-9470-77cd5ec67618.png)

Perfect! Thanks!

**Comment by sindrebroch** [comment] 2022-05-03 06:47
Seems the issue is resolved. Please reopen or open a new issue if there still are problems.

**Closed by sindrebroch** 2022-05-03 06:47 UTC

**Comment by janmatias** [comment] 2022-05-04 12:31
Yes, it works now, thanks!! :D
